%% INFO %%
% This function creates the vector p containing the full default set of
% parameters used by the host model. It also creates the vector Y0,
% which makes a 'guess' at initial conditions for the host. Improved
% initial conditions can be generated by simulating the host to steady
% state from this guess.
% (c) Copyright Dan Byrom and Alexander Darlington 2024.

function [p, Y0] = loadhostparameters()

%% OUTPUTS %%

% Define parameters
phie0 = 20; dyN = 0; influx = 1e12; dilution = 0.01;
vT = 726; vE = 5800; kT = 1e3; kE = 1e3;
wT = 4.14; wE = 4.14; wH = 949; wR = 930; wr = 3170;
oT = 4.38; oE = 4.38; oH = 4.38; oR = 427; or = 427;
nT = 300; nE = 300; nH = 300; nR = 7459;
bT = 0.95e-2; bE = 0.95e-2; bH = 0.95e-2; bR = 0.95e-2;
uT = 1; uE = 1; uH = 1; uR = 1;
dymT = 0.1; dymE = 0.1; dymH = 0.1; dymR = 0.1; dyrr = 0.1;
brho = 1; urho = 1; maxG = 1260; kG = 8e8; M0 = 1e8; kH = 152219; hH = 4;

% Set guess for initial conditions
xS = 1e12; N = 1000; iS = 1e3; ee = 1e3;
mT = 1; cT = 1; pT = 10;
mE = 1; cE = 1; pE = 10;
mH = 1; cH = 1; pH = 10;
mR = 1; cR = 1; pR = 10; r = 10; R = 10;

% Create vector outputs
p = [phie0; dyN; influx; dilution;
    vT; vE; kT; kE; wT; wE; wH; wR; wr;
    oT; oE; oH; oR; or; nT; nE; nH; nR;
    bT; bE; bH; bR; uT; uE; uH; uR;
    dymT; dymE; dymH; dymR; dyrr;
    brho; urho; maxG; kG; M0; kH; hH];

Y0 = [xS N iS ee mT cT pT mE cE pE mH cH pH mR cR pR r R];

end